#include "node_uuid.h"
#include "generic/typedef.h"

struct node_name {
    u16 uuid;
    const char *name;
};


const struct node_name node_name_list[] = {
    { NODE_UUID_SOURCE_DEV0, "source_dev0" },
    { NODE_UUID_SOURCE_DEV1, "source_dev1" },
    { NODE_UUID_SOURCE_DEV2, "source_dev2" },
    { NODE_UUID_SOURCE_DEV3, "source_dev3" },
    { NODE_UUID_SOURCE_DEV4, "source_dev4" },
    { NODE_UUID_LINEIN, "linein" },
    { NODE_UUID_SPDIF, "spdif" },
    { NODE_UUID_PC_SPK, "pc_spk" },
    { NODE_UUID_PC_MIC, "pc_mic" },
    { NODE_UUID_MUSIC, "music" },
    { NODE_UUID_PDM_MIC, "pdm_mic" },
    { NODE_UUID_FM, "fm" },
    { NODE_UUID_SPATIAL_EFFECTS, "spatial_effects" },
    { NODE_UUID_TONE, "tone" },
    { NODE_UUID_RING, "ring" },
    { NODE_UUID_KEY_TONE, "key_tone" },
    { NODE_UUID_AI_RX, "ai_rx" },
    { NODE_UUID_AI_TX, "ai_tx" },
    { NODE_UUID_CHANNLE_SWAP, "channel_swap" },
    { NODE_UUID_CVP_DEVELOP, "cvp_develop" },
    { NODE_UUID_CVP_DMS_ANS, "cvp_dms_ans" },
    { NODE_UUID_CVP_DMS_DNS, "cvp_dms_dns" },
    { NODE_UUID_CVP_SMS_ANS, "cvp_sms_ans" },
    { NODE_UUID_CVP_SMS_DNS, "cvp_sms_dns" },
    { NODE_UUID_CVP_DMS_FLEXIBLE_ANS, "cvp_dms_flexible_ans" },
    { NODE_UUID_CVP_DMS_FLEXIBLE_DNS, "cvp_dms_flexible_dns" },
    { NODE_UUID_CVP_DMS_HYBRID_DNS, "cvp_dms_hybrid_dns" },
    { NODE_UUID_CVP_DMS_AWN_DNS, "cvp_dms_awn_dns" },
    { NODE_UUID_ESCO_TX, "esco_tx" },
    { NODE_UUID_PLC, "plc" },
    { NODE_UUID_UART_DUMP, "uart_dump" },
    { NODE_UUID_EFFECT_DEV0, "effect_dev0" },
    { NODE_UUID_EFFECT_DEV1, "effect_dev1" },
    { NODE_UUID_EFFECT_DEV2, "effect_dev2" },
    { NODE_UUID_EFFECT_DEV3, "effect_dev3" },
    { NODE_UUID_EFFECT_DEV4, "effect_dev4" },
    { NODE_UUID_AGC, "agc" },
    { NODE_UUID_IIS0_TX, "iis0_tx" },
    { NODE_UUID_IIS0_RX, "iis0_rx" },
    { NODE_UUID_IIS1_TX, "iis1_tx" },
    { NODE_UUID_IIS1_RX, "iis1_rx" },
    { NODE_UUID_TDM_TX, "tdm_tx" },
    { NODE_UUID_TDM_RX, "tdm_rx" },
    { NODE_UUID_A2DP_RX, "a2dp_rx" },
    { NODE_UUID_ESCO_RX, "esco_rx" },
    { NODE_UUID_NOISE_SUPPRESSOR, "ns" },
    { NODE_UUID_NOISE_SUPPRESSOR_LITE, "ns_lite" },
    { NODE_UUID_SPATIAL_EFFECTS, "spatial_effects" },
    { NODE_UUID_SURROUND_DEMO, "surround_demo" },
    { NODE_UUID_VOLUME_CTRLER, "volume" },
    { NODE_UUID_CVP_3MIC, "cvp_3mic" },
    { NODE_UUID_SINK_DEV0, "sink_dev0" },
    { NODE_UUID_SINK_DEV1, "sink_dev1" },
    { NODE_UUID_SINK_DEV2, "sink_dev2" },
    { NODE_UUID_SINK_DEV3, "sink_dev3" },
    { NODE_UUID_SINK_DEV4, "sink_dev4" },
    { NODE_UUID_PC_MIC, "pc_mic" },
    { NODE_UUID_DATA_EXPORT, "data_export" },
    { NODE_UUID_DNS_NOISE_SUPPRESSOR, "dns" },
    { NODE_UUID_LE_AUDIO_SOURCE, "le_audio_source" },
    { NODE_UUID_LE_AUDIO_SINK, "le_audio_sink" },
    { NODE_UUID_LHDC_X, "lhdc_x" },
    { NODE_UUID_LOCAL_TWS_SOURCE, "local_tws_source" },
    { NODE_UUID_LOCAL_TWS_SINK, "local_tws_sink" },
    { NODE_UUID_MULTI_CH_IIS0_TX, "multi_ch_iis0" },
    { NODE_UUID_MULTI_CH_IIS1_TX, "multi_ch_iis1" },
    { NODE_UUID_SPDIF_MASTER, "spdif_master" },
    { NODE_UUID_MULTI_CH_TDM_TX, "multi_ch_tdm_tx" },
    { NODE_UUID_MULTI_CH_TDM_RX, "multi_ch_tdm_rx" },
    { NODE_UUID_VIRTUAL_UDISK, "virtual_udisk" },
    { NODE_UUID_CVP_SMS_VF, "cvp_sms_vf" },
    { NODE_UUID_CVP_V3, "cvp_v3" },
    { NODE_UUID_AUTODUCK, "autoduck" },
    { NODE_UUID_AUTODUCK_TRIGGER, "autoduck_trigger" },
    { NODE_UUID_AUTOMUTE, "auto_mute" },
    { NODE_UUID_AUTOTUNE, "autotune" },
    { NODE_UUID_3BAND_MERGE, "3band_merge" },
    { NODE_UUID_2BAND_MERGE, "2band_merge" },
    { NODE_UUID_BASS_TREBLE, "bass_treble_eq" },
    { NODE_UUID_BT_AUDIO_SYNC, "bt_audio_sync" },
    { NODE_UUID_CHANNEL_EXPANDER, "channel_expander" },
    { NODE_UUID_CHANNEL_MERGE, "channel_merge" },
    { NODE_UUID_CHORUS, "chorus" },
    { NODE_UUID_AUTOWAH, "autowah" },
    { NODE_UUID_CONVERT, "convert" },
    { NODE_UUID_BIT_WIDTH_CONVERT, "bit_width_convert" },
    { NODE_UUID_CROSSOVER, "crossover" },
    { NODE_UUID_CROSSOVER_2BAND, "crossover_2band" },
    { NODE_UUID_DAC, "dac" },
    { NODE_UUID_DECODER, "decoder" },
    { NODE_UUID_DYNAMIC_EQ_EXT_DETECTOR, "dynamic_eq_ext_det" },
    { NODE_UUID_DYNAMIC_EQ, "dynamic_eq" },
    { NODE_UUID_ECHO, "echo" },
    { NODE_UUID_ENCODER, "encoder" },
    { NODE_UUID_ENERGY_DETECT, "energy_detect" },
    { NODE_UUID_EQ, "eq" },
    { NODE_UUID_GAIN, "gain" },
    { NODE_UUID_HARMONIC_EXCITER, "harmonic_exciter" },
    { NODE_UUID_FREQUENCY_SHIFT, "howling" },
    { NODE_UUID_HOWLING_SUPPRESS, "howling_supress" },
    { NODE_UUID_INDICATOR, "indicator" },
    { NODE_UUID_MIXER, "mixer" },
    { NODE_UUID_MUTE, "mute" },
    { NODE_UUID_NOISEGATE, "ns_gate" },
    { NODE_UUID_NOISEGATE_PRO, "ns_gate_pro" },
    { NODE_UUID_FILE_PACKAGE, "package" },
    { NODE_UUID_PCM_DELAY, "pcm_delay" },
    { NODE_UUID_PITCH_SPEED, "pspeed" },
    { NODE_UUID_SRC, "resample" },
    { NODE_UUID_REVERB, "reverb" },
    { NODE_UUID_SOUND_SPLITTER, "sound_splitter" },
    { NODE_UUID_SOURCE, "source" },
    { NODE_UUID_SPECTRUM, "spectrum" },
    { NODE_UUID_SPEAKER_EQ, "spk_eq" },
    { NODE_UUID_STEREO_WIDENER, "stereo_widener" },
    { NODE_UUID_SURROUND, "sur" },
    { NODE_UUID_STEROMIX, "node_uuid_steromix" },
    { NODE_UUID_SPLIT_GAIN, "splitgain" },
    { NODE_UUID_VBASS, "virtual_bass" },
    { NODE_UUID_DATA_SATURATION, "data_saturation" },
    { NODE_UUID_VOCAL_REMOVER, "vocal_remover" },
    { NODE_UUID_VOCAL_TRACK_SEPARATION, "vocal_track_separation" },
    { NODE_UUID_VOCAL_TRACK_SYNTHESIS, "vocal_track" },
    { NODE_UUID_VOCAL_TRACK_SEPARATION_6TO2, "vocal_sep_6to2" },
    { NODE_UUID_VOCAL_TRACK_SEPARATION_8TO2, "vocal_sep_8to2" },
    { NODE_UUID_VOICE_CHANGER, "v_changer" },
    { NODE_UUID_VOICE_CHANGER_ADV, "v_changer_adv" },
    { NODE_UUID_WDRC_ADVANCE, "wdrc_advance" },
    { NODE_UUID_WDRC_DETECTOR, "wdrc_detector" },
    { NODE_UUID_WDRC, "wdrc" },
    { NODE_UUID_WRITE_FILE, "write_file" },
    { NODE_UUID_DYNAMIC_EQ_PRO_EXT_DETECTOR, "dynamic_eq_pro_ext_det" },
    { NODE_UUID_DYNAMIC_EQ_PRO, "dynamic_eq_pro" },
    { NODE_UUID_FADE, "fade" },
    { NODE_UUID_LLNS, "llns" },
    { NODE_UUID_PINGPONG_PCM_DELAY, "pingpong_pcm_delay" },
    { NODE_UUID_PLAY_SYNC, "play_sync" },
    { NODE_UUID_CAPTURE_SYNC, "capture_sync" },
    { NODE_UUID_DISTORTION_CLIPPING, "distortion_clipping" },
    { NODE_UUID_THREE_D, "three_d" },
    { NODE_UUID_DISTORTION, "distortion" },
    { NODE_UUID_SPECTRUM_ADVANCE, "spectrum_adv" },
    { NODE_UUID_HOWLING_GATE, "howling_gate" },
    { NODE_UUID_MDRC, "multiband_drc" },
    { NODE_UUID_STEREO_MTAPS_ECHO, "stereo_mtaps_echo" },
    { NODE_UUID_SWITCH, "switch" },
    { NODE_UUID_CHORUS_ADVANCE, "chorus_advance" },
    { NODE_UUID_FLANGER, "flanger" },
    { NODE_UUID_PHASER, "phaser" },
    { NODE_UUID_PINGPONG_ECHO, "pingpong_echo" },
    { NODE_UUID_FREQUENCY_COMPRESSOR, "frequency_compressor" },
    { NODE_UUID_HARMONY, "harmony" },
    { NODE_UUID_HOWLING_AHS, "howling_ahs" },
    { NODE_UUID_HOWLING_AHS_POST, "howling_ahs_post" },
    { NODE_UUID_LIMITER, "limiter" },
    { NODE_UUID_LLNS_DNS, "llns_dns" },
    { NODE_UUID_MULTIBAND_LIMITER, "multiband_limiter" },
    { NODE_UUID_NF_SUPPRESSOR, "noisefloor" },
    { NODE_UUID_PLATE_REVERB, "plate_reverb" },
    { NODE_UUID_PLATE_REVERB_ADVANCE, "reverb_advance" },
    { NODE_UUID_REPLACE, "replace" },
    { NODE_UUID_PLATE_REVERB_LITE, "reverb_lite" },
    { NODE_UUID_SOF_EQ, "sof_eq" },
    { NODE_UUID_SPATIAL_ADV, "spatial_adv" },
    { NODE_UUID_STEREO_SPATIAL_WIDER, "stereo_spatial_wider" },
    { NODE_UUID_TREMOLO, "tremolo" },
    { NODE_UUID_VIBRATO, "vibrato" },
    { NODE_UUID_VIRTUAL_BASS_CLASSIC, "virtual_bass_classic" },
    { NODE_UUID_VIRTUAL_BASS_PRO, "virtual_bass_pro" },
    { NODE_UUID_VIRTUAL_SURROUND_HP, "virtual_surround_hp" },
    { NODE_UUID_UPMIX_2TO5, "upmix_2to5" },
    { NODE_UUID_AVC, "avc" },
};


const char *jlstream_node_name(u16 node_uuid)
{
    for (int i = 0; i < ARRAY_SIZE(node_name_list); i++) {
        if (node_name_list[i].uuid == node_uuid) {
            return node_name_list[i].name;
        }
    }
    printf("unknow_node_name: %x\n", node_uuid);
    return "unknow";
}



